### ISSUE TITLE
Is OP2 support ARMV8 architecture

### ISSUE THREAD

**Issue by Qiyu8** [OP-DSL/OP2-Common#232] opened 2022-08-11 09:36 UTC
I want to use OP2 in my HPC apps, which mainly deployed in ARM based machine, is OP2 friendly enough to ARM?

**Comment by gihanmudalige** [comment] 2022-08-11 09:49
@Qiyu8 we have compiled and run on ARM systems before and have worked with the University of Bristol who hosts UKs Isambard HPC system that is ARM based. If you run into any issue on your side, will be happy to help, so simply flag in an issue here.

**Comment by gihanmudalige** [comment] 2022-08-11 10:38
I am assuming you are running your code with mpirun -np #number of procs
The MPI version needs careful handling as there is I/O (i.e. mesh generation or reading a mesh) to be considered. Can you give us a bit more detail on how this is done ?

**Comment by Qiyu8** [comment] 2022-08-11 11:18
The MPI version is openmpi-4.1.2, The mpi running command is :
X86:
`mpirun --allow-run-as-root -np 8 ../bin/xxx_mpi -i input.dat`
ARM:
`mpirun --allow-run-as-root -np 8 -mca pml ucx -mca btl ^vader,tcp,openib,uct ../bin/xxx_mpi -i input.dat`

**Comment by gihanmudalige** [comment] 2022-08-11 11:21
Ok, so how is the application reading input.dat and how is data distributed to each MPI proc ?
Have you looked at https://op2-dsl.readthedocs.io/en/latest/devapp.html  the tutorial that details the issues regarding distributed memory execution ?

**Comment by gihanmudalige** [comment] 2022-08-11 11:32
Interesting. So seems like you have the distribution of work to MPI procs done ok.  I wonder if there is some ARM specif issue for OpenMPI.  I assume you have already run our own Airfoil application and it also has the same issue on this ARM system ?

@reguly we had some of these runs on the Bristol machines, do you know what compiler and setup you used ?

**Comment by reguly** [comment] 2022-08-11 13:57
I think if the X86 version is working as expected, then it's unlikely to be an issue with OPS itself (or the application), as we don't have any separate code paths for X86 and ARM, it's more likely a configuration issue. Does this ARM CPU have multiple hardware threads per core (i.e. SMT8 for example)? It's possible all the ranks get assigned to the same physical core, and you don't see a speedup.

**Comment by lj-cug** [comment] 2022-08-12 01:43
Today I have run the airfoil case on the ARM machine, OK! Both the airfoil_openmp and airfoil_mpi can speedup the calculation. The wallclock time is 370.34 (s), 7.03(s), 27.16 (s) (using mpirun -np 16) for sequential, openmp and mpi cases running. Now the problem happened for MG-CFD case running, the mpi parallelism cannot function well. The difference between and airfoil and MGCFD is the multi-grid algorithm. So I have to check the code of MGCFD-OP2.
But the MPI version of MGCFD can function well in my X86 machine. Headache.

**Comment by lj-cug** [comment] 2022-08-12 07:12
The most time consumption kernels are compute_flux_edge_kernel and also the simple kernel "get_min_dt_kernel"
![mgcfd_mpi_node=4,N=32 ](https://user-images.githubusercontent.com/53997605/184303526-a4dd32e2-c1a6-44a2-b48d-5699d2290e0e.png)

**Comment by Qiyu8** [comment] 2022-08-12 09:16
@reguly I checked all of the ranks, They are running under different cores.

**Comment by reguly** [comment] 2022-08-12 09:24
Looking at the performance summary, note how "MPI time" is very large for a few loops, and "time" is only a bit larger. This means that these loops spend most of their time waiting on MPI communications, and very little time computing. So the issue is with MPI, or how its configured. I suspect if you look at the summary of airfoil, it will show similar (maybe not as extreme) numbers.

**Comment by lj-cug** [comment] 2022-08-13 08:59
After trying several optional running, I found that MPI version application can speedup when I use "mpirun -np 32 ../bin/mgcfd_mpi -i input.dat -m parmetis -r kway"
The domain decomposition algorithm in PARMETIS  and PTSCOTCH affect the mpi running efficiency on ARM machine. I found only the kway option can speedup, another two options including geom (default) and geomkway cannot speedup calculation on ARM machine. But all the three options can speedup MPI app on X86 machine.

**Comment by reguly** [comment] 2022-08-13 13:21
Interesting - I have seen parmetis + geom underperform, but it wasn't nearly this bad. What is the mesh you are using? Can you share timing results for kway?
I will do a pull request to make kway the default for MG-CFD

**Comment by reguly** [comment] 2022-08-14 05:12
Using Kway is now default in mg-cfd: https://github.com/warwick-hpsc/MG-CFD-app-OP2/pull/45

**Comment by lj-cug** [comment] 2022-08-14 08:17
I have use Rotor_1M case to test the MGCFD-OP2-app on Huawei 920 ARM machine, and now gives the initial report as following:
 app name        Max total runtime (s)
mgcfd_seq:      116.44 
mgcfd_openmp:     6.89 (It seems that app only use the 32 cores in one NUMA domain)
mgcfd_cuda:       4.23 (We use one A100 Nvidia GPU on the node)
mgcfd_mpi:        3.05 (-np 64 ../bin/mgcfd_mpi -i input.dat -m parmetis -r kway)
                109.60 (-np 64 ../bin/mgcfd_mpi -i input.dat -m parmetis -r geom)
                108.78 (-np 64 ../bin/mgcfd_mpi -i input.dat -m parmetis -r geomkway)
mgcfd_mpi_openmp:  158.42   (-np=1, OMP_NUM_THREADS=64)
mgcfd_mpi_openmp:  144.99   (-np=1, OMP_NUM_THREADS=32)
mgcfd_mpi_openmp:    3.28   (-np=64, OMP_NUM_THREADS=1) (Now we use the 64 cores in the 2 NUMA domains)
mgcfd_mpi_openmp:    5.59   (-np=32, OMP_NUM_THREADS=1)

**Comment by reguly** [comment] 2022-08-14 11:44
Interesting stuff! This is a dual-socket machine, right? For MPI+OpenMP, you should try using two processes, and bind them each to their own socket. e.g. if you use OpenMPI:
`OMP_NUM_THREADS=32 mpirun --bind-to socket -np 2 ../bin/mgcfd_mpi_openmp`
Generally speaking, if you have a larger Rotor37 mesh, these differences should reduce.

**Comment by lj-cug** [comment] 2022-08-15 01:22
Yes! We can speedup when we run "mpirun -np 2 --bind-to socket -x OMP_NUM_THREADS=32 ../bin/mgcfd_mpi_openmp -i input.dat -m parmetis -r kway"
But we failed to speedup when we use "--bind-to core" instead of using "--bind-to socket"
I should study the domain decomposition affecting the MPI communication on ARM machine when we use multigrid CFD. It's strange. There's no problem in the case of airfoil using simple spatial discretisation scheme.

**Closed** 2023-02-11 12:57 UTC
